"""add_audit_log_and_knowledge_base_tables

Revision ID: 0a0b52e64917
Revises: ab366bf211ff
Create Date: 2026-05-29 11:29:00.939005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0b52e64917'
down_revision: Union[str, Sequence[str], None] = 'ab366bf211ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
