"""add billing_records, paid_at columns and user patient_id fk

Revision ID: 7a0dc7baa503
Revises: dad75d363958
Create Date: 2026-06-12 19:36:44.610891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a0dc7baa503'
down_revision: Union[str, Sequence[str], None] = 'dad75d363958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
