"""add total_fee and settled to admission

Revision ID: ab366bf211ff
Revises: 
Create Date: 2026-05-16 16:25:00.758402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ab366bf211ff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admissions', sa.Column('status', sa.String(length=20), nullable=True))
    op.alter_column('admissions', 'total_fee',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('admissions', 'settled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admissions', 'settled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('admissions', 'total_fee',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.drop_column('admissions', 'status')
    # ### end Alembic commands ###
