"""add billing_records, paid_at columns and user patient_id fk

Revision ID: dad75d363958
Revises: 0a0b52e64917
Create Date: 2026-06-12 19:29:52.016994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad75d363958'
down_revision: Union[str, Sequence[str], None] = '0a0b52e64917'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bill_no', sa.String(length=30), nullable=False),
    sa.Column('charge_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('paid_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('charge_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('remark', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_no')
    )
    op.add_column('admissions', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.add_column('prescriptions', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.add_column('registrations', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('patient_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'patients', ['patient_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'patient_id')
    op.drop_column('registrations', 'paid_at')
    op.drop_column('prescriptions', 'paid_at')
    op.drop_column('admissions', 'paid_at')
    op.drop_table('billing_records')
    # ### end Alembic commands ###
